import React from 'react'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import { AppHeader } from '@/widgets/app-header/app-header'
import { cn } from '@/components/ui/utils'
import { AppFooter } from '@/widgets/app-footer/app-footer'

const manrope = Manrope({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Web studio | by david_gri',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen bg-background', manrope.className)}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  )
}
